version: "1.0"
services:
  postgres:
    container_name: flexy-postgres
    image: postgres
    ports:
      - "5454:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres